# Generated by Django 4.1.7 on 2023-05-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cricket',
            fields=[
                ('Team', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
